services:
  - type: web
    name: fsrs-app
    env: python
    buildCommand: pip install -r fsrs_web/requirements.txt
    startCommand: cd fsrs_web && gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 